version: '3.8'

services:
  idem:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: idem
    ports:
      - "80:80"
    restart: always
    networks:
      - idem

  idem-api:
    image: ghcr.io/idem-ia/idem-api:latest
    container_name: idem-api
    environment:
      DEEPSEEK_API_KEY: "${DEEPSEEK_API_KEY}"
      GEMINI_API_KEY: "${GEMINI_API_KEY}"
      PORT: "${PORT}"
      FIREBASE_API_KEY: "${FIREBASE_API_KEY}"
      FIREBASE_AUTH_DOMAIN: "${FIREBASE_AUTH_DOMAIN}"
      FIREBASE_PROJECT_ID: "${FIREBASE_PROJECT_ID}"
      FIREBASE_STORAGE_BUCKET: "${FIREBASE_STORAGE_BUCKET}"
      FIREBASE_MESSAGING_SENDER_ID: "${FIREBASE_MESSAGING_SENDER_ID}"
      FIREBASE_APP_ID: "${FIREBASE_APP_ID}"
      FIREBASE_PRIVATE_KEY: "${FIREBASE_PRIVATE_KEY}"
      FIREBASE_CLIENT_EMAIL: "${FIREBASE_CLIENT_EMAIL}"
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    networks:
      - idem

  idem-webgen:
    image: ghcr.io/idem-ia/idem-webgen:latest
    container_name: idem-webgen
    ports:
      - '5173:5173'
    environment:
      VITE_LOG_LEVEL: "${VITE_LOG_LEVEL}"
      VITE_API_BASE_URL: "${VITE_API_BASE_URL}"
      GEMINI_API_KEY: "${GEMINI_API_KEY}"
    networks:
      - idem

  idem-chart:
    image: ghcr.io/mermaid-js/mermaid-live-editor
    container_name: idem-chart
    ports:
      - "8040:8080"
    platform: linux/amd64
    restart: unless-stopped
    networks:
      - idem

networks:
  idem:
    driver: bridge
